name: projet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.13.4
  firebase_auth: ^4.15.1
  firebase_core: ^2.24.1
  firebase_storage: ^11.5.6
  firebase_ui_auth: ^1.11.0
  flutter:
    sdk: flutter
  flutter_flushbar: ^0.0.2
  image_picker: ^1.0.4
  fluttertoast: ^8.0.8
  camera: ^0.10.5+6
  tflite_v2: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite
